# -*- mode: python ; coding: utf-8 -*-
# ArmorPilot — onefile build (single self-contained .exe, no extra files needed)

a = Analysis(
    ['tools/launcher_win.py'],
    pathex=[],
    binaries=[],
    datas=[
        ('app/templates', 'app/templates'),
        ('app/static', 'app/static'),
    ],
    hiddenimports=[
        'cryptography',
        'cryptography.hazmat.primitives.asymmetric.ed25519',
        'cryptography.hazmat.primitives.serialization',
        'cryptography.hazmat.primitives.serialization.base',
        'waitress',
        'waitress.server',
        'kubernetes',
        'kubernetes.client',
        'kubernetes.config',
        'dotenv',
        'app.build_profile',
        'app.config',
        'app.db',
        'app.auth',
        'app.license',
        'app.installation',
        'app.fingerprint',
        'app.k8s_client',
        'app.product',
        'app.audit',
        'app.policy_templates',
        'app.routes',
        'app.routes.api',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
    optimize=0,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='ArmorPilot',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
