apiVersion: v1
kind: ServiceAccount
metadata:
  name: varmor-console-sa
  namespace: default

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: varmor-console-role
rules:
  - apiGroups: ["apps"]
    resources: ["deployments", "statefulsets", "daemonsets"]
    verbs: ["get", "list", "watch", "patch"]

  - apiGroups: [""]
    resources: ["pods", "namespaces"]
    verbs: ["get", "list", "watch"]

  - apiGroups: ["crd.varmor.org"]
    resources: ["varmorpolicies", "varmorclusterpolicies", "armorprofilemodels", "armorprofiles"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: varmor-console-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: varmor-console-role
subjects:
  - kind: ServiceAccount
    name: varmor-console-sa
    namespace: default
