import copy


PACKS = [
    {
        "id": "baseline",
        "name": "Baseline Hardening",
        "description": "Production-ready guardrails for common Kubernetes workloads.",
        "order": 10,
    },
    {
        "id": "cve",
        "name": "CVE Mitigation",
        "description": "Focused mitigations for common container escape and kernel attack paths.",
        "order": 20,
    },
    {
        "id": "compliance",
        "name": "Compliance",
        "description": "Least-privilege templates aligned with audit and regulated workload needs.",
        "order": 30,
    },
    {
        "id": "workload",
        "name": "Workload Type",
        "description": "Starting policies for common application runtime patterns.",
        "order": 40,
    },
    {
        "id": "network",
        "name": "Network Egress",
        "description": "NetworkProxy and BPF egress-control templates.",
        "order": 50,
    },
]


TEMPLATES = [
    {
        "id": "baseline-production",
        "pack": "baseline",
        "name": "Production Baseline",
        "summary": "Balanced AppArmor and Seccomp protections for normal production workloads.",
        "risk": "medium",
        "mode": "EnhanceProtect",
        "enforcers": ["AppArmor", "Seccomp"],
        "rules": [
            "disable-cap-privileged",
            "disallow-abuse-user-ns",
            "disallow-create-user-ns",
            "disallow-load-all-bpf-prog",
            "disallow-userfaultfd-creation",
            "disable-access-shadow",
            "disable-access-ssh-dir",
        ],
        "capability_rules": ["NET_RAW", "SYS_PTRACE"],
        "banned_files": ["/etc/shadow", "/root/.ssh/**", "/home/*/.ssh/**"],
        "test_steps": [
            "Run a shell inside the workload and verify /etc/shadow access is denied.",
            "Try unshare --user and verify the action is blocked or audited.",
        ],
    },
    {
        "id": "baseline-sensitive-files",
        "pack": "baseline",
        "name": "Sensitive File Guard",
        "summary": "Blocks credential and host-sensitive file access with low operational blast radius.",
        "risk": "low",
        "mode": "EnhanceProtect",
        "enforcers": ["AppArmor", "BPF"],
        "rules": [
            "disable-access-shadow",
            "disable-access-passwd",
            "disable-access-ssh-dir",
            "mitigate-sa-leak",
        ],
        "banned_files": [
            "/var/run/secrets/kubernetes.io/serviceaccount/**",
            "/etc/shadow",
            "/root/.ssh/**",
            "/home/*/.ssh/**",
            "/var/run/docker.sock",
            "/run/containerd/containerd.sock",
        ],
        "test_steps": [
            "Read /var/run/secrets/kubernetes.io/serviceaccount/token from the container.",
            "Read /etc/shadow and confirm a violation is logged.",
        ],
    },
    {
        "id": "baseline-privileged-lockdown",
        "pack": "baseline",
        "name": "Privileged Workload Lockdown",
        "summary": "Baseline for unavoidable privileged workloads; blocks mount and escape paths.",
        "risk": "high",
        "mode": "EnhanceProtect",
        "enforcers": ["AppArmor", "BPF", "Seccomp"],
        "rules": [
            "disable-cap-privileged",
            "disallow-write-core-pattern",
            "disallow-mount-securityfs",
            "disallow-write-release-agent",
            "disallow-mount-cgroupfs",
            "disallow-mount-procfs",
            "disallow-debug-disk-device",
            "disallow-mount-disk-device",
        ],
        "privileged": True,
        "bpf_mounts": [
            {
                "sourcePattern": "/**",
                "fstype": "securityfs",
                "flags": [],
                "qualifiers": ["deny"],
            },
            {
                "sourcePattern": "/dev/**",
                "fstype": "",
                "flags": [],
                "qualifiers": ["deny"],
            },
        ],
        "test_steps": [
            "Try writing /proc/sys/kernel/core_pattern.",
            "Try mounting securityfs and verify denial.",
        ],
    },
    {
        "id": "baseline-observe-first",
        "pack": "baseline",
        "name": "Observe First",
        "summary": "BehaviorModeling template for learning workload behavior before enforcement.",
        "risk": "low",
        "mode": "BehaviorModeling",
        "enforcers": ["AppArmor", "Seccomp"],
        "modeling_duration": 60,
        "test_steps": [
            "Exercise normal application traffic during the modeling window.",
            "Review ArmorProfileModel before converting to DefenseInDepth.",
        ],
    },
    {
        "id": "baseline-defense-from-model",
        "pack": "baseline",
        "name": "DefenseInDepth from Model",
        "summary": "Strict allowlist mode intended after behavior modeling has completed.",
        "risk": "high",
        "mode": "DefenseInDepth",
        "enforcers": ["AppArmor", "Seccomp"],
        "did_apparmor_type": "BehaviorModel",
        "did_seccomp_type": "BehaviorModel",
        "did_allow_violations": True,
        "test_steps": [
            "Apply in allow-violations mode first.",
            "Inspect violations, then disable allow-violations for enforcement.",
        ],
    },
    {
        "id": "cve-2019-5736-runc",
        "pack": "cve",
        "name": "CVE-2019-5736 runc Override",
        "summary": "Mitigates runc binary overwrite and common post-exploit tooling.",
        "risk": "medium",
        "mode": "EnhanceProtect",
        "enforcers": ["AppArmor"],
        "rules": [
            "runc-override-mitigation",
            "disable-shell",
            "disable-wget",
            "disable-curl",
            "disable-chmod-x-bit",
        ],
        "test_steps": [
            "Attempt a runc overwrite proof-of-concept in a lab namespace.",
            "Confirm the overwrite path is denied and logged.",
        ],
    },
    {
        "id": "cve-2022-0492-cgroups",
        "pack": "cve",
        "name": "CVE-2022-0492 cgroups Escape",
        "summary": "Blocks core_pattern and release_agent escape primitives.",
        "risk": "high",
        "mode": "EnhanceProtect",
        "enforcers": ["AppArmor"],
        "rules": [
            "cgroups-lxcfs-escape-mitigation",
            "disallow-write-core-pattern",
            "disallow-write-release-agent",
            "disallow-mount-cgroupfs",
            "disable-cap-privileged",
        ],
        "privileged": True,
        "test_steps": [
            "Try echoing a payload into /proc/sys/kernel/core_pattern.",
            "Try writing cgroup release_agent and verify denial.",
        ],
    },
    {
        "id": "cve-2022-0847-dirty-pipe",
        "pack": "cve",
        "name": "CVE-2022-0847 Dirty Pipe",
        "summary": "Applies vArmor Dirty Pipe mitigation with supporting procfs restrictions.",
        "risk": "medium",
        "mode": "EnhanceProtect",
        "enforcers": ["AppArmor"],
        "rules": [
            "dirty-pipe-mitigation",
            "disallow-access-procfs-root",
            "disable-access-shadow",
        ],
        "test_steps": [
            "Run the Dirty Pipe lab exploit against a non-production target.",
            "Confirm writes to protected host-sensitive paths fail.",
        ],
    },
    {
        "id": "cve-2025-1974-ingress-nightmare",
        "pack": "cve",
        "name": "CVE-2025-1974 IngressNightmare",
        "summary": "Applies the IngressNightmare mitigation rule for ingress controller workloads.",
        "risk": "medium",
        "mode": "EnhanceProtect",
        "enforcers": ["AppArmor"],
        "rules": ["ingress-nightmare-mitigation", "disable-access-shadow"],
        "test_steps": [
            "Apply only to ingress controller workloads first.",
            "Run smoke tests for normal ingress reload and request handling.",
        ],
    },
    {
        "id": "cve-userns-ebpf-abuse",
        "pack": "cve",
        "name": "UserNS and eBPF Abuse Block",
        "summary": "Blocks user namespace creation and eBPF loading primitives used by many exploits.",
        "risk": "medium",
        "mode": "EnhanceProtect",
        "enforcers": ["AppArmor", "Seccomp"],
        "rules": [
            "disallow-abuse-user-ns",
            "disallow-create-user-ns",
            "disallow-load-all-bpf-prog",
            "disallow-load-bpf-via-setsockopt",
        ],
        "test_steps": [
            "Run unshare --user --map-root-user in the workload.",
            "Try a small bpf() loader and verify it is blocked.",
        ],
    },
    {
        "id": "compliance-cis-restricted",
        "pack": "compliance",
        "name": "CIS-style Restricted Workload",
        "summary": "Least-privilege controls aligned with restricted workload expectations.",
        "risk": "medium",
        "mode": "EnhanceProtect",
        "enforcers": ["AppArmor", "Seccomp"],
        "rules": [
            "disable-cap-all-except-net-bind-service",
            "disallow-abuse-user-ns",
            "disallow-create-user-ns",
            "disallow-mount",
            "disallow-load-all-bpf-prog",
            "disable-access-shadow",
            "disable-access-ssh-dir",
            "disable-su-sudo",
        ],
        "test_steps": [
            "Verify app does not require Linux capabilities beyond NET_BIND_SERVICE.",
            "Run normal readiness and liveness probes after applying.",
        ],
    },
    {
        "id": "compliance-pci-sensitive",
        "pack": "compliance",
        "name": "PCI-sensitive Application",
        "summary": "Protects secrets, service account tokens, metadata endpoints, and runtime sockets.",
        "risk": "medium",
        "mode": "EnhanceProtect",
        "enforcers": ["AppArmor", "BPF", "Seccomp"],
        "rules": [
            "disable-cap-privileged",
            "mitigate-sa-leak",
            "block-access-to-metadata-service",
            "block-access-to-kube-apiserver",
            "block-access-to-container-runtime",
            "disable-access-shadow",
            "disable-access-ssh-dir",
        ],
        "banned_files": [
            "/var/run/secrets/kubernetes.io/serviceaccount/**",
            "/var/run/docker.sock",
            "/run/containerd/containerd.sock",
        ],
        "test_steps": [
            "Attempt to curl cloud metadata and kube-apiserver from the pod.",
            "Confirm service account token access is denied if the app does not need it.",
        ],
    },
    {
        "id": "compliance-prod-namespace-guardrail",
        "pack": "compliance",
        "name": "Production Namespace Guardrail",
        "summary": "General production namespace guardrail with audit enabled for tuning.",
        "risk": "medium",
        "mode": "EnhanceProtect",
        "enforcers": ["AppArmor", "BPF", "Seccomp"],
        "rules": [
            "disable-cap-privileged",
            "disallow-abuse-user-ns",
            "disallow-load-all-bpf-prog",
            "block-access-to-container-runtime",
            "block-access-to-metadata-service",
            "disable-access-shadow",
        ],
        "audit_violations": True,
        "test_steps": [
            "Apply to a canary workload first.",
            "Review violation logs before broad namespace rollout.",
        ],
    },
    {
        "id": "compliance-internal-only-service",
        "pack": "compliance",
        "name": "Internal-only Service",
        "summary": "Allows only private-network egress and blocks public outbound access.",
        "risk": "medium",
        "mode": "EnhanceProtect",
        "enforcers": ["BPF", "NetworkProxy"],
        "rules": ["block-access-to-metadata-service"],
        "np_egress": {
            "defaultAction": "deny",
            "rules": [
                {
                    "qualifiers": ["allow"],
                    "cidr": "10.0.0.0/8",
                    "ports": [{"port": 80}, {"port": 443}],
                    "description": "allow private service traffic",
                },
                {
                    "qualifiers": ["allow"],
                    "cidr": "172.16.0.0/12",
                    "ports": [{"port": 80}, {"port": 443}],
                    "description": "allow private service traffic",
                },
                {
                    "qualifiers": ["allow"],
                    "cidr": "192.168.0.0/16",
                    "ports": [{"port": 80}, {"port": 443}],
                    "description": "allow private service traffic",
                },
            ],
        },
        "test_steps": [
            "Test calls to required internal services.",
            "Verify public internet egress is denied.",
        ],
    },
    {
        "id": "workload-nginx-static",
        "pack": "workload",
        "name": "Nginx / Static Web",
        "summary": "Restricts shell/tooling while preserving normal web serving behavior.",
        "risk": "low",
        "mode": "EnhanceProtect",
        "enforcers": ["AppArmor", "Seccomp"],
        "rules": [
            "disable-cap-all-except-net-bind-service",
            "disable-shell",
            "disable-wget",
            "disable-curl",
            "disable-access-shadow",
            "disallow-create-user-ns",
        ],
        "test_steps": [
            "Run HTTP smoke tests on exposed paths.",
            "Try shell execution from the container.",
        ],
    },
    {
        "id": "workload-java-spring",
        "pack": "workload",
        "name": "Java Spring Boot API",
        "summary": "Protects Java service workloads without blocking JVM startup patterns.",
        "risk": "low",
        "mode": "EnhanceProtect",
        "enforcers": ["AppArmor", "BPF"],
        "rules": [
            "disable-cap-privileged",
            "disable-access-shadow",
            "disable-access-ssh-dir",
            "block-access-to-metadata-service",
            "disable-su-sudo",
        ],
        "banned_files": ["/var/run/docker.sock", "/run/containerd/containerd.sock"],
        "test_steps": [
            "Restart the service and verify JVM startup still succeeds.",
            "Run application health and representative API calls.",
        ],
    },
    {
        "id": "workload-node-api",
        "pack": "workload",
        "name": "Node.js API",
        "summary": "Blocks shell, package-manager style tooling, secrets, and metadata access.",
        "risk": "medium",
        "mode": "EnhanceProtect",
        "enforcers": ["AppArmor", "BPF"],
        "rules": [
            "disable-cap-privileged",
            "disable-shell",
            "disable-wget",
            "disable-curl",
            "disable-chmod-x-bit",
            "disable-access-shadow",
            "block-access-to-metadata-service",
        ],
        "test_steps": [
            "Run normal Node.js API requests.",
            "Verify child shell execution is not required before enforcing.",
        ],
    },
    {
        "id": "workload-python-fastapi",
        "pack": "workload",
        "name": "Python / FastAPI",
        "summary": "Restricts host-sensitive access and common post-exploitation utilities.",
        "risk": "medium",
        "mode": "EnhanceProtect",
        "enforcers": ["AppArmor", "BPF"],
        "rules": [
            "disable-cap-privileged",
            "disable-access-shadow",
            "disable-access-ssh-dir",
            "disable-wget",
            "disable-curl",
            "block-access-to-metadata-service",
        ],
        "banned_files": ["/var/run/docker.sock", "/run/containerd/containerd.sock"],
        "test_steps": [
            "Run health checks and normal request handlers.",
            "Confirm the app does not shell out to curl or wget in normal operation.",
        ],
    },
    {
        "id": "workload-db-client",
        "pack": "workload",
        "name": "Database Client Service",
        "summary": "Allows database egress to private ranges and blocks metadata/runtime sockets.",
        "risk": "medium",
        "mode": "EnhanceProtect",
        "enforcers": ["BPF", "NetworkProxy"],
        "rules": ["block-access-to-metadata-service", "block-access-to-container-runtime"],
        "np_egress": {
            "defaultAction": "deny",
            "rules": [
                {
                    "qualifiers": ["allow"],
                    "cidr": "10.0.0.0/8",
                    "ports": [{"port": 5432}, {"port": 3306}, {"port": 6379}],
                    "description": "allow private database ports",
                }
            ],
        },
        "test_steps": [
            "Test database connectivity to required destinations.",
            "Verify non-database outbound access is denied.",
        ],
    },
    {
        "id": "workload-cicd-runner",
        "pack": "workload",
        "name": "CI/CD Runner Audit",
        "summary": "Audit-oriented template for build runners where enforcement needs tuning.",
        "risk": "medium",
        "mode": "EnhanceProtect",
        "enforcers": ["AppArmor", "BPF", "Seccomp"],
        "rules": [
            "block-access-to-metadata-service",
            "block-access-to-container-runtime",
            "disallow-load-all-bpf-prog",
        ],
        "audit_violations": True,
        "allow_violations": True,
        "test_steps": [
            "Run representative pipeline jobs.",
            "Convert noisy audit entries into explicit allow or deny rules before enforcing.",
        ],
    },
    {
        "id": "network-block-cloud-metadata",
        "pack": "network",
        "name": "Block Cloud Metadata",
        "summary": "Blocks common cloud metadata endpoints through BPF attack-protection rules.",
        "risk": "low",
        "mode": "EnhanceProtect",
        "enforcers": ["BPF"],
        "rules": [
            "block-access-to-metadata-service",
            "block-access-to-aws-metadata-service",
            "block-access-to-volc-metadata-service",
            "block-access-to-alibaba-metadata-service",
            "block-access-to-oci-metadata-service",
        ],
        "bpf_network": {
            "egress": {
                "toDestinations": [
                    {
                        "qualifiers": ["deny"],
                        "cidr": "169.254.169.254/32",
                        "ports": [{"protocol": "TCP", "port": 80}],
                    }
                ]
            }
        },
        "test_steps": [
            "Try curl http://169.254.169.254/ from the workload.",
            "Confirm denial appears in violation logs.",
        ],
    },
    {
        "id": "network-default-deny-private-allow",
        "pack": "network",
        "name": "Default Deny, Private Allow",
        "summary": "NetworkProxy default-deny policy allowing HTTP(S) to RFC1918 networks.",
        "risk": "medium",
        "mode": "EnhanceProtect",
        "enforcers": ["BPF", "NetworkProxy"],
        "np_egress": {
            "defaultAction": "deny",
            "rules": [
                {"qualifiers": ["allow"], "cidr": "10.0.0.0/8", "ports": [{"port": 80}, {"port": 443}]},
                {"qualifiers": ["allow"], "cidr": "172.16.0.0/12", "ports": [{"port": 80}, {"port": 443}]},
                {"qualifiers": ["allow"], "cidr": "192.168.0.0/16", "ports": [{"port": 80}, {"port": 443}]},
            ],
        },
        "test_steps": [
            "Test required internal HTTP(S) calls.",
            "Confirm internet egress is denied.",
        ],
    },
    {
        "id": "network-l7-http-allowlist",
        "pack": "network",
        "name": "L7 HTTP Allowlist",
        "summary": "Allows selected hosts, paths, and HTTP methods through NetworkProxy.",
        "risk": "medium",
        "mode": "EnhanceProtect",
        "enforcers": ["BPF", "NetworkProxy"],
        "np_egress": {
            "defaultAction": "deny",
            "httpRules": [
                {
                    "qualifiers": ["allow"],
                    "description": "allow approved API paths",
                    "match": {
                        "hosts": ["api.internal.example.com"],
                        "ports": [{"port": 80}, {"port": 443}],
                        "paths": [{"prefix": "/api"}],
                        "methods": ["GET", "POST"],
                    },
                }
            ],
        },
        "test_steps": [
            "Replace api.internal.example.com with real approved hosts.",
            "Test allowed and denied paths before applying broadly.",
        ],
    },
    {
        "id": "network-egress-audit-discovery",
        "pack": "network",
        "name": "Egress Audit Discovery",
        "summary": "Default-allow egress template with audit rules for discovering dependencies.",
        "risk": "low",
        "mode": "EnhanceProtect",
        "enforcers": ["BPF", "NetworkProxy"],
        "audit_violations": True,
        "np_egress": {
            "defaultAction": "allow",
            "rules": [
                {
                    "qualifiers": ["audit"],
                    "cidr": "0.0.0.0/0",
                    "ports": [{"port": 80}, {"port": 443}],
                    "description": "audit outbound web dependencies",
                }
            ],
        },
        "test_steps": [
            "Run the workload through normal traffic.",
            "Use observed destinations to build a stricter allowlist.",
        ],
    },
]


def get_policy_templates_payload() -> dict:
    return {
        "packs": copy.deepcopy(PACKS),
        "templates": copy.deepcopy(TEMPLATES),
        "total": len(TEMPLATES),
    }
