import copy


PACKS = [
    {
        "id": "baseline",
        "name": "Baseline Hardening",
        "description": "Production-ready guardrails for common Kubernetes workloads.",
        "order": 10,
    },
    {
        "id": "cve",
        "name": "CVE Mitigation",
        "description": "Focused mitigations for common container escape and kernel attack paths.",
        "order": 20,
    },
    {
        "id": "compliance",
        "name": "Compliance",
        "description": "Least-privilege templates aligned with audit and regulated workload needs.",
        "order": 30,
    },
    {
        "id": "workload",
        "name": "Workload Type",
        "description": "Starting policies for common application runtime patterns.",
        "order": 40,
    },
    {
        "id": "network",
        "name": "Network Egress",
        "description": "NetworkProxy and BPF egress-control templates.",
        "order": 50,
    },
]


TEMPLATES = [
    {
        "id": "baseline-production",
        "pack": "baseline",
        "name": "Production Baseline",
        "summary": "Balanced AppArmor and Seccomp protections for normal production workloads.",
        "risk": "medium",
        "mode": "EnhanceProtect",
        "enforcers": ["AppArmor", "Seccomp"],
        "rules": [
            "disable-cap-privileged",
            "disallow-abuse-user-ns",
            "disallow-create-user-ns",
            "disallow-load-all-bpf-prog",
            "disallow-userfaultfd-creation",
            "disable-access-shadow",
            "disable-access-ssh-dir",
        ],
        "capability_rules": ["NET_RAW", "SYS_PTRACE"],
        "banned_files": ["/etc/shadow", "/root/.ssh/**", "/home/*/.ssh/**"],
        "test_steps": [
            "Run a shell inside the workload and verify /etc/shadow access is denied.",
            "Try unshare --user and verify the action is blocked or audited.",
        ],
    },
    {
        "id": "baseline-sensitive-files",
        "pack": "baseline",
        "name": "Sensitive File Guard",
        "summary": "Blocks credential and host-sensitive file access with low operational blast radius.",
        "risk": "low",
        "mode": "EnhanceProtect",
        "enforcers": ["AppArmor", "BPF"],
        "rules": [
            "disable-access-shadow",
            "disable-access-passwd",
            "disable-access-ssh-dir",
            "mitigate-sa-leak",
        ],
        "banned_files": [
            "/var/run/secrets/kubernetes.io/serviceaccount/**",
            "/etc/shadow",
            "/root/.ssh/**",
            "/home/*/.ssh/**",
            "/var/run/docker.sock",
            "/run/containerd/containerd.sock",
        ],
        "test_steps": [
            "Read /var/run/secrets/kubernetes.io/serviceaccount/token from the container.",
            "Read /etc/shadow and confirm a violation is logged.",
        ],
    },
    {
        "id": "baseline-privileged-lockdown",
        "pack": "baseline",
        "name": "Privileged Workload Lockdown",
        "summary": "Baseline for unavoidable privileged workloads; blocks mount and escape paths.",
        "risk": "high",
        "mode": "EnhanceProtect",
        "enforcers": ["AppArmor", "BPF", "Seccomp"],
        "rules": [
            "disable-cap-privileged",
            "disallow-write-core-pattern",
            "disallow-mount-securityfs",
            "disallow-write-release-agent",
            "disallow-mount-cgroupfs",
            "disallow-mount-procfs",
            "disallow-debug-disk-device",
            "disallow-mount-disk-device",
        ],
        "privileged": True,
        "bpf_mounts": [
            {
                "sourcePattern": "/**",
                "fstype": "securityfs",
                "flags": [],
                "qualifiers": ["deny"],
            },
            {
                "sourcePattern": "/dev/**",
                "fstype": "",
                "flags": [],
                "qualifiers": ["deny"],
            },
        ],
        "test_steps": [
            "Try writing /proc/sys/kernel/core_pattern.",
            "Try mounting securityfs and verify denial.",
        ],
    },
    {
        "id": "baseline-observe-first",
        "pack": "baseline",
        "name": "Observe First",
        "summary": "BehaviorModeling template for learning workload behavior before enforcement.",
        "risk": "low",
        "mode": "BehaviorModeling",
        "enforcers": ["AppArmor", "Seccomp"],
        "modeling_duration": 60,
        "test_steps": [
            "Exercise normal application traffic during the modeling window.",
            "Review ArmorProfileModel before converting to DefenseInDepth.",
        ],
    },
    {
        "id": "baseline-defense-from-model",
        "pack": "baseline",
        "name": "DefenseInDepth from Model",
        "summary": "Strict allowlist mode intended after behavior modeling has completed.",
        "risk": "high",
        "mode": "DefenseInDepth",
        "enforcers": ["AppArmor", "Seccomp"],
        "did_apparmor_type": "BehaviorModel",
        "did_seccomp_type": "BehaviorModel",
        "did_allow_violations": True,
        "test_steps": [
            "Apply in allow-violations mode first.",
            "Inspect violations, then disable allow-violations for enforcement.",
        ],
    },
    {
        "id": "cve-2019-5736-runc",
        "pack": "cve",
        "name": "CVE-2019-5736 runc Override",
        "summary": "Mitigates runc binary overwrite and common post-exploit tooling.",
        "risk": "medium",
        "mode": "EnhanceProtect",
        "enforcers": ["AppArmor"],
        "rules": [
            "runc-override-mitigation",
            "disable-shell",
            "disable-wget",
            "disable-curl",
            "disable-chmod-x-bit",
        ],
        "test_steps": [
            "Attempt a runc overwrite proof-of-concept in a lab namespace.",
            "Confirm the overwrite path is denied and logged.",
        ],
    },
    {
        "id": "cve-2022-0492-cgroups",
        "pack": "cve",
        "name": "CVE-2022-0492 cgroups Escape",
        "summary": "Blocks core_pattern and release_agent escape primitives.",
        "risk": "high",
        "mode": "EnhanceProtect",
        "enforcers": ["AppArmor"],
        "rules": [
            "cgroups-lxcfs-escape-mitigation",
            "disallow-write-core-pattern",
            "disallow-write-release-agent",
            "disallow-mount-cgroupfs",
            "disable-cap-privileged",
        ],
        "privileged": True,
        "test_steps": [
            "Try echoing a payload into /proc/sys/kernel/core_pattern.",
            "Try writing cgroup release_agent and verify denial.",
        ],
    },
    {
        "id": "cve-2022-0847-dirty-pipe",
        "pack": "cve",
        "name": "CVE-2022-0847 Dirty Pipe",
        "summary": "Applies vArmor Dirty Pipe mitigation with supporting procfs restrictions.",
        "risk": "medium",
        "mode": "EnhanceProtect",
        "enforcers": ["AppArmor"],
        "rules": [
            "dirty-pipe-mitigation",
            "disallow-access-procfs-root",
            "disable-access-shadow",
        ],
        "test_steps": [
            "Run the Dirty Pipe lab exploit against a non-production target.",
            "Confirm writes to protected host-sensitive paths fail.",
        ],
    },
    {
        "id": "cve-2025-1974-ingress-nightmare",
        "pack": "cve",
        "name": "CVE-2025-1974 IngressNightmare",
        "summary": "Applies the IngressNightmare mitigation rule for ingress controller workloads.",
        "risk": "medium",
        "mode": "EnhanceProtect",
        "enforcers": ["AppArmor"],
        "rules": ["ingress-nightmare-mitigation", "disable-access-shadow"],
        "test_steps": [
            "Apply only to ingress controller workloads first.",
            "Run smoke tests for normal ingress reload and request handling.",
        ],
    },
    {
        "id": "cve-userns-ebpf-abuse",
        "pack": "cve",
        "name": "UserNS and eBPF Abuse Block",
        "summary": "Blocks user namespace creation and eBPF loading primitives used by many exploits.",
        "risk": "medium",
        "mode": "EnhanceProtect",
        "enforcers": ["AppArmor", "Seccomp"],
        "rules": [
            "disallow-abuse-user-ns",
            "disallow-create-user-ns",
            "disallow-load-all-bpf-prog",
            "disallow-load-bpf-via-setsockopt",
        ],
        "test_steps": [
            "Run unshare --user --map-root-user in the workload.",
            "Try a small bpf() loader and verify it is blocked.",
        ],
    },
    {
        "id": "compliance-cis-restricted",
        "pack": "compliance",
        "name": "CIS-style Restricted Workload",
        "summary": "Least-privilege controls aligned with restricted workload expectations.",
        "risk": "medium",
        "mode": "EnhanceProtect",
        "enforcers": ["AppArmor", "Seccomp"],
        "rules": [
            "disable-cap-all-except-net-bind-service",
            "disallow-abuse-user-ns",
            "disallow-create-user-ns",
            "disallow-mount",
            "disallow-load-all-bpf-prog",
            "disable-access-shadow",
            "disable-access-ssh-dir",
            "disable-su-sudo",
        ],
        "test_steps": [
            "Verify app does not require Linux capabilities beyond NET_BIND_SERVICE.",
            "Run normal readiness and liveness probes after applying.",
        ],
    },
    {
        "id": "compliance-pci-sensitive",
        "pack": "compliance",
        "name": "PCI-sensitive Application",
        "summary": "Protects secrets, service account tokens, metadata endpoints, and runtime sockets.",
        "risk": "medium",
        "mode": "EnhanceProtect",
        "enforcers": ["AppArmor", "BPF", "Seccomp"],
        "rules": [
            "disable-cap-privileged",
            "mitigate-sa-leak",
            "block-access-to-metadata-service",
            "block-access-to-kube-apiserver",
            "block-access-to-container-runtime",
            "disable-access-shadow",
            "disable-access-ssh-dir",
        ],
        "banned_files": [
            "/var/run/secrets/kubernetes.io/serviceaccount/**",
            "/var/run/docker.sock",
            "/run/containerd/containerd.sock",
        ],
        "test_steps": [
            "Attempt to curl cloud metadata and kube-apiserver from the pod.",
            "Confirm service account token access is denied if the app does not need it.",
        ],
    },
    {
        "id": "compliance-prod-namespace-guardrail",
        "pack": "compliance",
        "name": "Production Namespace Guardrail",
        "summary": "General production namespace guardrail with audit enabled for tuning.",
        "risk": "medium",
        "mode": "EnhanceProtect",
        "enforcers": ["AppArmor", "BPF", "Seccomp"],
        "rules": [
            "disable-cap-privileged",
            "disallow-abuse-user-ns",
            "disallow-load-all-bpf-prog",
            "block-access-to-container-runtime",
            "block-access-to-metadata-service",
            "disable-access-shadow",
        ],
        "audit_violations": True,
        "test_steps": [
            "Apply to a canary workload first.",
            "Review violation logs before broad namespace rollout.",
        ],
    },
    {
        "id": "compliance-internal-only-service",
        "pack": "compliance",
        "name": "Internal-only Service",
        "summary": "Allows only private-network egress and blocks public outbound access.",
        "risk": "medium",
        "mode": "EnhanceProtect",
        "enforcers": ["BPF", "NetworkProxy"],
        "rules": ["block-access-to-metadata-service"],
        "np_egress": {
            "defaultAction": "deny",
            "rules": [
                {
                    "qualifiers": ["allow"],
                    "cidr": "10.0.0.0/8",
                    "ports": [{"port": 80}, {"port": 443}],
                    "description": "allow private service traffic",
                },
                {
                    "qualifiers": ["allow"],
                    "cidr": "172.16.0.0/12",
                    "ports": [{"port": 80}, {"port": 443}],
                    "description": "allow private service traffic",
                },
                {
                    "qualifiers": ["allow"],
                    "cidr": "192.168.0.0/16",
                    "ports": [{"port": 80}, {"port": 443}],
                    "description": "allow private service traffic",
                },
            ],
        },
        "test_steps": [
            "Test calls to required internal services.",
            "Verify public internet egress is denied.",
        ],
    },
    {
        "id": "workload-nginx-static",
        "pack": "workload",
        "name": "Nginx / Static Web",
        "summary": "Restricts shell/tooling while preserving normal web serving behavior.",
        "risk": "low",
        "mode": "EnhanceProtect",
        "enforcers": ["AppArmor", "Seccomp"],
        "rules": [
            "disable-cap-all-except-net-bind-service",
            "disable-shell",
            "disable-wget",
            "disable-curl",
            "disable-access-shadow",
            "disallow-create-user-ns",
        ],
        "test_steps": [
            "Run HTTP smoke tests on exposed paths.",
            "Try shell execution from the container.",
        ],
    },
    {
        "id": "workload-java-spring",
        "pack": "workload",
        "name": "Java Spring Boot API",
        "summary": "Protects Java service workloads without blocking JVM startup patterns.",
        "risk": "low",
        "mode": "EnhanceProtect",
        "enforcers": ["AppArmor", "BPF"],
        "rules": [
            "disable-cap-privileged",
            "disable-access-shadow",
            "disable-access-ssh-dir",
            "block-access-to-metadata-service",
            "disable-su-sudo",
        ],
        "banned_files": ["/var/run/docker.sock", "/run/containerd/containerd.sock"],
        "test_steps": [
            "Restart the service and verify JVM startup still succeeds.",
            "Run application health and representative API calls.",
        ],
    },
    {
        "id": "workload-node-api",
        "pack": "workload",
        "name": "Node.js API",
        "summary": "Blocks shell, package-manager style tooling, secrets, and metadata access.",
        "risk": "medium",
        "mode": "EnhanceProtect",
        "enforcers": ["AppArmor", "BPF"],
        "rules": [
            "disable-cap-privileged",
            "disable-shell",
            "disable-wget",
            "disable-curl",
            "disable-chmod-x-bit",
            "disable-access-shadow",
            "block-access-to-metadata-service",
        ],
        "test_steps": [
            "Run normal Node.js API requests.",
            "Verify child shell execution is not required before enforcing.",
        ],
    },
    {
        "id": "workload-python-fastapi",
        "pack": "workload",
        "name": "Python / FastAPI",
        "summary": "Restricts host-sensitive access and common post-exploitation utilities.",
        "risk": "medium",
        "mode": "EnhanceProtect",
        "enforcers": ["AppArmor", "BPF"],
        "rules": [
            "disable-cap-privileged",
            "disable-access-shadow",
            "disable-access-ssh-dir",
            "disable-wget",
            "disable-curl",
            "block-access-to-metadata-service",
        ],
        "banned_files": ["/var/run/docker.sock", "/run/containerd/containerd.sock"],
        "test_steps": [
            "Run health checks and normal request handlers.",
            "Confirm the app does not shell out to curl or wget in normal operation.",
        ],
    },
    {
        "id": "workload-db-client",
        "pack": "workload",
        "name": "Database Client Service",
        "summary": "Allows database egress to private ranges and blocks metadata/runtime sockets.",
        "risk": "medium",
        "mode": "EnhanceProtect",
        "enforcers": ["BPF", "NetworkProxy"],
        "rules": ["block-access-to-metadata-service", "block-access-to-container-runtime"],
        "np_egress": {
            "defaultAction": "deny",
            "rules": [
                {
                    "qualifiers": ["allow"],
                    "cidr": "10.0.0.0/8",
                    "ports": [{"port": 5432}, {"port": 3306}, {"port": 6379}],
                    "description": "allow private database ports",
                }
            ],
        },
        "test_steps": [
            "Test database connectivity to required destinations.",
            "Verify non-database outbound access is denied.",
        ],
    },
    {
        "id": "workload-cicd-runner",
        "pack": "workload",
        "name": "CI/CD Runner Audit",
        "summary": "Audit-oriented template for build runners where enforcement needs tuning.",
        "risk": "medium",
        "mode": "EnhanceProtect",
        "enforcers": ["AppArmor", "BPF", "Seccomp"],
        "rules": [
            "block-access-to-metadata-service",
            "block-access-to-container-runtime",
            "disallow-load-all-bpf-prog",
        ],
        "audit_violations": True,
        "allow_violations": True,
        "test_steps": [
            "Run representative pipeline jobs.",
            "Convert noisy audit entries into explicit allow or deny rules before enforcing.",
        ],
    },
    {
        "id": "network-block-cloud-metadata",
        "pack": "network",
        "name": "Block Cloud Metadata",
        "summary": "Blocks common cloud metadata endpoints through BPF attack-protection rules.",
        "risk": "low",
        "mode": "EnhanceProtect",
        "enforcers": ["BPF"],
        "rules": [
            "block-access-to-metadata-service",
            "block-access-to-aws-metadata-service",
            "block-access-to-volc-metadata-service",
            "block-access-to-alibaba-metadata-service",
            "block-access-to-oci-metadata-service",
        ],
        "bpf_network": {
            "egress": {
                "toDestinations": [
                    {
                        "qualifiers": ["deny"],
                        "cidr": "169.254.169.254/32",
                        "ports": [{"protocol": "TCP", "port": 80}],
                    }
                ]
            }
        },
        "test_steps": [
            "Try curl http://169.254.169.254/ from the workload.",
            "Confirm denial appears in violation logs.",
        ],
    },
    {
        "id": "network-default-deny-private-allow",
        "pack": "network",
        "name": "Default Deny, Private Allow",
        "summary": "NetworkProxy default-deny policy allowing HTTP(S) to RFC1918 networks.",
        "risk": "medium",
        "mode": "EnhanceProtect",
        "enforcers": ["BPF", "NetworkProxy"],
        "np_egress": {
            "defaultAction": "deny",
            "rules": [
                {"qualifiers": ["allow"], "cidr": "10.0.0.0/8", "ports": [{"port": 80}, {"port": 443}]},
                {"qualifiers": ["allow"], "cidr": "172.16.0.0/12", "ports": [{"port": 80}, {"port": 443}]},
                {"qualifiers": ["allow"], "cidr": "192.168.0.0/16", "ports": [{"port": 80}, {"port": 443}]},
            ],
        },
        "test_steps": [
            "Test required internal HTTP(S) calls.",
            "Confirm internet egress is denied.",
        ],
    },
    {
        "id": "network-l7-http-allowlist",
        "pack": "network",
        "name": "L7 HTTP Allowlist",
        "summary": "Allows selected hosts, paths, and HTTP methods through NetworkProxy.",
        "risk": "medium",
        "mode": "EnhanceProtect",
        "enforcers": ["BPF", "NetworkProxy"],
        "np_egress": {
            "defaultAction": "deny",
            "httpRules": [
                {
                    "qualifiers": ["allow"],
                    "description": "allow approved API paths",
                    "match": {
                        "hosts": ["api.internal.example.com"],
                        "ports": [{"port": 80}, {"port": 443}],
                        "paths": [{"prefix": "/api"}],
                        "methods": ["GET", "POST"],
                    },
                }
            ],
        },
        "test_steps": [
            "Replace api.internal.example.com with real approved hosts.",
            "Test allowed and denied paths before applying broadly.",
        ],
    },
    {
        "id": "network-egress-audit-discovery",
        "pack": "network",
        "name": "Egress Audit Discovery",
        "summary": "Default-allow egress template with audit rules for discovering dependencies.",
        "risk": "low",
        "mode": "EnhanceProtect",
        "enforcers": ["BPF", "NetworkProxy"],
        "audit_violations": True,
        "np_egress": {
            "defaultAction": "allow",
            "rules": [
                {
                    "qualifiers": ["audit"],
                    "cidr": "0.0.0.0/0",
                    "ports": [{"port": 80}, {"port": 443}],
                    "description": "audit outbound web dependencies",
                }
            ],
        },
        "test_steps": [
            "Run the workload through normal traffic.",
            "Use observed destinations to build a stricter allowlist.",
        ],
    },
    {
        "id": "workload-untrusted-third-party",
        "pack": "workload",
        "name": "Untrusted Third-party Image Guard",
        "summary": "Defense pack for workloads from vendors or sources you do not fully trust.",
        "risk": "high",
        "mode": "EnhanceProtect",
        "enforcers": ["AppArmor", "BPF", "Seccomp"],
        "rules": [
            "disable-cap-privileged",
            "disable-shell",
            "disable-wget",
            "disable-curl",
            "disable-chmod-x-bit",
            "disable-su-sudo",
            "disable-access-shadow",
            "disable-access-ssh-dir",
            "mitigate-sa-leak",
            "block-access-to-metadata-service",
            "block-access-to-kube-apiserver",
            "block-access-to-container-runtime",
            "disallow-abuse-user-ns",
            "disallow-create-user-ns",
            "disallow-load-all-bpf-prog",
        ],
        "capability_rules": ["NET_RAW", "SYS_ADMIN", "SYS_PTRACE", "DAC_READ_SEARCH"],
        "banned_files": [
            "/var/run/secrets/kubernetes.io/serviceaccount/**",
            "/var/run/docker.sock",
            "/run/containerd/containerd.sock",
            "/var/run/crio/crio.sock",
            "/etc/shadow",
            "/root/.ssh/**",
            "/home/*/.ssh/**",
        ],
        "bpf_process_rules": [
            {"pattern": "/usr/bin/apt", "permissions": ["exec"], "qualifiers": ["deny"]},
            {"pattern": "/usr/bin/apk", "permissions": ["exec"], "qualifiers": ["deny"]},
            {"pattern": "/usr/bin/yum", "permissions": ["exec"], "qualifiers": ["deny"]},
            {"pattern": "/usr/bin/dnf", "permissions": ["exec"], "qualifiers": ["deny"]},
            {"pattern": "/usr/bin/pip", "permissions": ["exec"], "qualifiers": ["deny"]},
            {"pattern": "/usr/bin/npm", "permissions": ["exec"], "qualifiers": ["deny"]},
        ],
        "prerequisites": [
            "Use a dedicated namespace and service account.",
            "Remove serviceAccount token automount unless the app needs Kubernetes API access.",
            "Apply Kubernetes Pod Security Admission restricted where possible.",
        ],
        "recommended_security_context": {
            "runAsNonRoot": True,
            "allowPrivilegeEscalation": False,
            "readOnlyRootFilesystem": True,
            "capabilities": {"drop": ["ALL"]},
            "seccompProfile": {"type": "RuntimeDefault"},
        },
        "test_steps": [
            "Try shell, curl, package-manager, and service-account-token access from the container.",
            "Verify normal application health checks still pass before enforcing broadly.",
        ],
    },
    {
        "id": "compliance-no-kubernetes-api-access",
        "pack": "compliance",
        "name": "No Kubernetes API Access",
        "summary": "Blocks service account token usage and kube-apiserver access for ordinary apps.",
        "risk": "medium",
        "mode": "EnhanceProtect",
        "enforcers": ["AppArmor", "BPF"],
        "rules": [
            "mitigate-sa-leak",
            "block-access-to-kube-apiserver",
            "block-access-to-metadata-service",
            "disable-access-shadow",
        ],
        "banned_files": [
            "/var/run/secrets/kubernetes.io/serviceaccount/**",
            "/run/secrets/kubernetes.io/serviceaccount/**",
        ],
        "prerequisites": [
            "Set automountServiceAccountToken=false when the app does not call the Kubernetes API.",
            "Confirm sidecars and agents in the pod do not need the token before enforcing.",
        ],
        "recommended_security_context": {
            "automountServiceAccountToken": False,
            "runAsNonRoot": True,
            "allowPrivilegeEscalation": False,
        },
        "test_steps": [
            "Run kubernetes.default.svc and service account token access checks from the pod.",
            "Watch violation logs for unexpected platform-sidecar dependencies.",
        ],
    },
    {
        "id": "baseline-runtime-socket-guard",
        "pack": "baseline",
        "name": "Runtime Socket Guard",
        "summary": "Blocks Docker, containerd, CRI-O, and Kubernetes runtime sockets from workloads.",
        "risk": "low",
        "mode": "EnhanceProtect",
        "enforcers": ["AppArmor", "BPF"],
        "rules": ["block-access-to-container-runtime", "disable-access-shadow"],
        "banned_files": [
            "/var/run/docker.sock",
            "/run/docker.sock",
            "/run/containerd/containerd.sock",
            "/var/run/containerd/containerd.sock",
            "/var/run/crio/crio.sock",
            "/run/crio/crio.sock",
            "/var/lib/kubelet/pki/**",
        ],
        "bpf_file_rules": [
            {"pattern": "/var/run/docker.sock", "permissions": ["read", "write"], "qualifiers": ["deny"]},
            {"pattern": "/run/containerd/containerd.sock", "permissions": ["read", "write"], "qualifiers": ["deny"]},
            {"pattern": "/var/run/crio/crio.sock", "permissions": ["read", "write"], "qualifiers": ["deny"]},
        ],
        "prerequisites": [
            "Remove hostPath mounts for runtime sockets wherever possible.",
            "Use build services or isolated runners instead of mounting docker.sock into app pods.",
        ],
        "test_steps": [
            "Attempt ls/connect/read operations against known runtime socket paths.",
            "Confirm normal app startup does not depend on host runtime sockets.",
        ],
    },
    {
        "id": "compliance-secret-exfiltration-guard",
        "pack": "compliance",
        "name": "Secret Exfiltration Guard",
        "summary": "Reduces common secret theft paths after application compromise.",
        "risk": "medium",
        "mode": "EnhanceProtect",
        "enforcers": ["AppArmor", "BPF"],
        "rules": [
            "mitigate-sa-leak",
            "disable-access-shadow",
            "disable-access-passwd",
            "disable-access-ssh-dir",
            "block-access-to-metadata-service",
            "disable-wget",
            "disable-curl",
        ],
        "banned_files": [
            "/var/run/secrets/kubernetes.io/serviceaccount/**",
            "/run/secrets/**",
            "/etc/shadow",
            "/proc/*/environ",
            "/root/.ssh/**",
            "/home/*/.ssh/**",
            "/root/.aws/**",
            "/home/*/.aws/**",
            "/root/.config/gcloud/**",
            "/home/*/.config/gcloud/**",
        ],
        "prerequisites": [
            "Prefer short-lived workload identity over long-lived file-based credentials.",
            "Review apps that legitimately read /proc/*/environ before enforcement.",
        ],
        "test_steps": [
            "Try reading service account token, /proc/1/environ, and common cloud credential paths.",
            "Confirm secrets are not logged by app startup or debug handlers.",
        ],
    },
    {
        "id": "workload-immutable-app-runtime",
        "pack": "workload",
        "name": "Immutable App Runtime",
        "summary": "Prevents runtime mutation of application and OS directories.",
        "risk": "high",
        "mode": "EnhanceProtect",
        "enforcers": ["AppArmor", "BPF"],
        "rules": [
            "disable-write-etc",
            "disable-chmod-x-bit",
            "disable-chmod-s-bit",
            "disable-wget",
            "disable-curl",
            "disable-shell",
        ],
        "bpf_file_rules": [
            {"pattern": "/bin/**", "permissions": ["write", "append"], "qualifiers": ["deny"]},
            {"pattern": "/sbin/**", "permissions": ["write", "append"], "qualifiers": ["deny"]},
            {"pattern": "/usr/**", "permissions": ["write", "append"], "qualifiers": ["deny"]},
            {"pattern": "/lib/**", "permissions": ["write", "append"], "qualifiers": ["deny"]},
            {"pattern": "/lib64/**", "permissions": ["write", "append"], "qualifiers": ["deny"]},
            {"pattern": "/app/**", "permissions": ["write", "append"], "qualifiers": ["deny"]},
        ],
        "bpf_process_rules": [
            {"pattern": "/usr/bin/apt", "permissions": ["exec"], "qualifiers": ["deny"]},
            {"pattern": "/usr/bin/apk", "permissions": ["exec"], "qualifiers": ["deny"]},
            {"pattern": "/usr/bin/yum", "permissions": ["exec"], "qualifiers": ["deny"]},
            {"pattern": "/usr/bin/dnf", "permissions": ["exec"], "qualifiers": ["deny"]},
        ],
        "prerequisites": [
            "Mount writable data at explicit paths such as /tmp, /var/tmp, or application data volumes.",
            "Use readOnlyRootFilesystem=true when the workload supports it.",
        ],
        "recommended_security_context": {
            "readOnlyRootFilesystem": True,
            "allowPrivilegeEscalation": False,
            "capabilities": {"drop": ["ALL"]},
        },
        "test_steps": [
            "Try writing to /usr, /app, /etc, and package-manager paths.",
            "Run normal startup and update jobs to confirm no runtime self-mutation is required.",
        ],
    },
    {
        "id": "workload-public-web-api-guard",
        "pack": "workload",
        "name": "Public-facing Web/API Guard",
        "summary": "Hardens internet-facing services against common post-compromise actions.",
        "risk": "medium",
        "mode": "EnhanceProtect",
        "enforcers": ["AppArmor", "BPF", "Seccomp"],
        "rules": [
            "disable-cap-privileged",
            "disable-shell",
            "disable-wget",
            "disable-curl",
            "disable-su-sudo",
            "disable-access-shadow",
            "disable-access-ssh-dir",
            "block-access-to-metadata-service",
            "block-access-to-container-runtime",
            "disallow-create-user-ns",
            "disallow-load-all-bpf-prog",
        ],
        "audit_violations": True,
        "banned_files": [
            "/var/run/secrets/kubernetes.io/serviceaccount/**",
            "/var/run/docker.sock",
            "/run/containerd/containerd.sock",
        ],
        "prerequisites": [
            "Confirm the app does not spawn shell commands for normal request handling.",
            "Pair with ingress/WAF controls for HTTP-layer attacks.",
        ],
        "test_steps": [
            "Run health, login, upload, and key public API workflows.",
            "Try shell/curl/metadata access from a compromised request handler.",
        ],
    },
    {
        "id": "workload-cicd-runner-strict",
        "pack": "workload",
        "name": "CI/CD Runner Strict Isolation",
        "summary": "Strict profile for build runners that should not touch host runtime or metadata.",
        "risk": "high",
        "mode": "EnhanceProtect",
        "enforcers": ["BPF", "NetworkProxy", "Seccomp"],
        "rules": [
            "block-access-to-metadata-service",
            "block-access-to-kube-apiserver",
            "block-access-to-container-runtime",
            "disallow-create-user-ns",
            "disallow-load-all-bpf-prog",
        ],
        "bpf_file_rules": [
            {"pattern": "/var/run/docker.sock", "permissions": ["read", "write"], "qualifiers": ["deny"]},
            {"pattern": "/run/containerd/containerd.sock", "permissions": ["read", "write"], "qualifiers": ["deny"]},
        ],
        "bpf_process_rules": [
            {"pattern": "/usr/bin/docker", "permissions": ["exec"], "qualifiers": ["deny"]},
            {"pattern": "/usr/bin/kubectl", "permissions": ["exec"], "qualifiers": ["deny"]},
            {"pattern": "/usr/bin/ssh", "permissions": ["exec"], "qualifiers": ["audit"]},
        ],
        "np_egress": {
            "defaultAction": "deny",
            "httpRules": [
                {
                    "qualifiers": ["allow"],
                    "description": "allow source control and registry endpoints",
                    "match": {
                        "hosts": ["git.example.com", "registry.example.com"],
                        "ports": [{"port": 443}],
                        "methods": ["GET", "POST", "PUT", "PATCH"],
                    },
                }
            ],
        },
        "prerequisites": [
            "Use isolated runner namespaces and per-project service accounts.",
            "Replace placeholder hosts with real Git and registry endpoints.",
            "Use remote builders instead of host docker.sock when possible.",
        ],
        "test_steps": [
            "Run representative build, test, and image-push jobs.",
            "Verify access to host docker.sock, metadata, and kube-apiserver is denied.",
        ],
    },
    {
        "id": "network-build-registry-egress-only",
        "pack": "network",
        "name": "Build Job Registry Egress Only",
        "summary": "Default-deny egress profile for build jobs that only need Git and registry endpoints.",
        "risk": "medium",
        "mode": "EnhanceProtect",
        "enforcers": ["BPF", "NetworkProxy"],
        "rules": ["block-access-to-metadata-service"],
        "np_egress": {
            "defaultAction": "deny",
            "httpRules": [
                {
                    "qualifiers": ["allow"],
                    "description": "source repository",
                    "match": {"hosts": ["git.example.com"], "ports": [{"port": 443}]},
                },
                {
                    "qualifiers": ["allow"],
                    "description": "container registry",
                    "match": {"hosts": ["registry.example.com"], "ports": [{"port": 443}]},
                },
            ],
        },
        "prerequisites": [
            "Replace placeholder hosts with your SCM and registry domains.",
            "Add package mirror domains only when builds need dependency downloads.",
        ],
        "test_steps": [
            "Run a build that clones source and pushes an image.",
            "Try outbound access to an unapproved internet endpoint and verify denial.",
        ],
    },
    {
        "id": "network-east-west-lateral-guard",
        "pack": "network",
        "name": "East-West Lateral Movement Guard",
        "summary": "Blocks broad intra-cluster movement; allows only explicit service CIDR traffic.",
        "risk": "medium",
        "mode": "EnhanceProtect",
        "enforcers": ["BPF", "NetworkProxy"],
        "np_egress": {
            "defaultAction": "deny",
            "rules": [
                {
                    "qualifiers": ["allow"],
                    "cidr": "10.96.0.0/12",
                    "ports": [{"port": 80}, {"port": 443}],
                    "description": "replace with approved service CIDR and ports",
                }
            ],
        },
        "prerequisites": [
            "Replace 10.96.0.0/12 with the real Kubernetes service CIDR or approved service ranges.",
            "Add DNS allow rules separately when needed.",
        ],
        "test_steps": [
            "Test required service-to-service calls.",
            "Attempt access to unrelated namespace services and verify denial.",
        ],
    },
    {
        "id": "network-dns-egress-guard",
        "pack": "network",
        "name": "DNS Egress Guard",
        "summary": "Allows DNS only to the cluster DNS service and blocks direct external DNS.",
        "risk": "medium",
        "mode": "EnhanceProtect",
        "enforcers": ["BPF", "NetworkProxy"],
        "np_egress": {
            "defaultAction": "deny",
            "rules": [
                {
                    "qualifiers": ["allow"],
                    "ip": "10.96.0.10",
                    "ports": [{"port": 53}],
                    "description": "replace with kube-dns/CoreDNS service IP",
                },
                {
                    "qualifiers": ["allow"],
                    "cidr": "10.0.0.0/8",
                    "ports": [{"port": 80}, {"port": 443}],
                    "description": "approved private service egress",
                },
            ],
        },
        "prerequisites": [
            "Replace 10.96.0.10 with your kube-dns/CoreDNS service IP.",
            "Confirm workloads do not need direct DNS to public resolvers.",
        ],
        "test_steps": [
            "Run nslookup through cluster DNS.",
            "Try DNS to 8.8.8.8 or 1.1.1.1 and verify it is denied.",
        ],
    },
    {
        "id": "baseline-admin-debug-pod-audit",
        "pack": "baseline",
        "name": "Admin Debug Pod Audit",
        "summary": "Audit-first template for temporary debug pods without immediately breaking workflows.",
        "risk": "low",
        "mode": "EnhanceProtect",
        "enforcers": ["AppArmor", "BPF"],
        "rules": [
            "block-access-to-metadata-service",
            "block-access-to-container-runtime",
            "mitigate-sa-leak",
            "disable-access-shadow",
        ],
        "audit_violations": True,
        "allow_violations": True,
        "test_steps": [
            "Use this for temporary debug workloads, then review violation logs.",
            "Convert repeated dangerous access into enforced deny templates.",
        ],
    },
    {
        "id": "baseline-host-namespace-damage-reduction",
        "pack": "baseline",
        "name": "Host Namespace Damage Reduction",
        "summary": "Damage-reduction template for workloads that temporarily need host namespace access.",
        "risk": "high",
        "mode": "EnhanceProtect",
        "enforcers": ["AppArmor", "BPF", "Seccomp"],
        "rules": [
            "disable-cap-privileged",
            "disallow-write-core-pattern",
            "disallow-mount-securityfs",
            "disallow-write-release-agent",
            "disallow-mount-procfs",
            "disallow-mount-cgroupfs",
            "disallow-debug-disk-device",
            "disallow-access-procfs-root",
            "disallow-access-kallsyms",
            "disallow-create-user-ns",
        ],
        "privileged": True,
        "bpf_mounts": [
            {"sourcePattern": "/proc/**", "fstype": "", "flags": [], "qualifiers": ["deny"]},
            {"sourcePattern": "/sys/**", "fstype": "", "flags": [], "qualifiers": ["deny"]},
            {"sourcePattern": "/dev/**", "fstype": "", "flags": [], "qualifiers": ["deny"]},
        ],
        "prerequisites": [
            "Use only for workloads that cannot avoid hostPID, hostNetwork, hostPath, or privileged mode.",
            "Prefer removing host namespace access instead of relying on runtime blocking.",
        ],
        "test_steps": [
            "Test required host-level functionality explicitly.",
            "Attempt procfs, sysfs, cgroupfs, and device-node access that the workload should not need.",
        ],
    },
    {
        "id": "workload-package-manager-block",
        "pack": "workload",
        "name": "Package Manager Block",
        "summary": "Blocks package managers and download tools in immutable runtime containers.",
        "risk": "medium",
        "mode": "EnhanceProtect",
        "enforcers": ["AppArmor", "BPF"],
        "rules": [
            "disable-wget",
            "disable-curl",
            "disable-chmod-x-bit",
            "disable-shell",
        ],
        "bpf_process_rules": [
            {"pattern": "/usr/bin/apt", "permissions": ["exec"], "qualifiers": ["deny"]},
            {"pattern": "/usr/bin/apt-get", "permissions": ["exec"], "qualifiers": ["deny"]},
            {"pattern": "/usr/bin/apk", "permissions": ["exec"], "qualifiers": ["deny"]},
            {"pattern": "/usr/bin/yum", "permissions": ["exec"], "qualifiers": ["deny"]},
            {"pattern": "/usr/bin/dnf", "permissions": ["exec"], "qualifiers": ["deny"]},
            {"pattern": "/usr/bin/pip", "permissions": ["exec"], "qualifiers": ["deny"]},
            {"pattern": "/usr/bin/pip3", "permissions": ["exec"], "qualifiers": ["deny"]},
            {"pattern": "/usr/bin/npm", "permissions": ["exec"], "qualifiers": ["deny"]},
            {"pattern": "/usr/bin/npx", "permissions": ["exec"], "qualifiers": ["deny"]},
            {"pattern": "/usr/bin/gem", "permissions": ["exec"], "qualifiers": ["deny"]},
        ],
        "prerequisites": [
            "Build dependencies into the image instead of installing them at runtime.",
            "Confirm entrypoint scripts do not call package managers.",
        ],
        "test_steps": [
            "Try apt/apk/yum/dnf/pip/npm from an exec shell.",
            "Run normal app startup and verify it does not install dependencies dynamically.",
        ],
    },
    {
        "id": "workload-database-exfiltration-guard",
        "pack": "workload",
        "name": "Database Exfiltration Guard",
        "summary": "Limits database client workloads to approved DB ports and blocks exfil tooling.",
        "risk": "medium",
        "mode": "EnhanceProtect",
        "enforcers": ["BPF", "NetworkProxy"],
        "rules": ["block-access-to-metadata-service", "block-access-to-container-runtime"],
        "bpf_process_rules": [
            {"pattern": "/usr/bin/curl", "permissions": ["exec"], "qualifiers": ["deny"]},
            {"pattern": "/usr/bin/wget", "permissions": ["exec"], "qualifiers": ["deny"]},
            {"pattern": "/bin/sh", "permissions": ["exec"], "qualifiers": ["audit"]},
        ],
        "np_egress": {
            "defaultAction": "deny",
            "rules": [
                {
                    "qualifiers": ["allow"],
                    "cidr": "10.0.0.0/8",
                    "ports": [{"port": 5432}, {"port": 3306}, {"port": 6379}, {"port": 27017}],
                    "description": "approved private database ranges",
                }
            ],
        },
        "prerequisites": [
            "Replace 10.0.0.0/8 with approved database CIDRs.",
            "Add any required telemetry endpoints deliberately rather than allowing broad egress.",
        ],
        "test_steps": [
            "Test database connectivity and migration jobs.",
            "Try curl/wget and arbitrary outbound HTTPS from the workload.",
        ],
    },
    {
        "id": "compliance-multitenant-namespace-guardrail",
        "pack": "compliance",
        "name": "Multi-tenant Namespace Guardrail",
        "summary": "Guardrail for tenant workloads with default-deny egress and restricted kernel behavior.",
        "risk": "high",
        "mode": "EnhanceProtect",
        "enforcers": ["BPF", "NetworkProxy", "Seccomp"],
        "rules": [
            "block-access-to-metadata-service",
            "block-access-to-kube-apiserver",
            "block-access-to-container-runtime",
            "disallow-create-user-ns",
            "disallow-load-all-bpf-prog",
            "disallow-userfaultfd-creation",
        ],
        "np_egress": {
            "defaultAction": "deny",
            "rules": [
                {
                    "qualifiers": ["allow"],
                    "ip": "10.96.0.10",
                    "ports": [{"port": 53}],
                    "description": "replace with kube-dns/CoreDNS service IP",
                }
            ],
        },
        "prerequisites": [
            "Use namespace-level RBAC isolation and Pod Security Admission restricted.",
            "Replace the DNS IP and add explicit tenant-approved egress destinations.",
            "Use ResourceQuota and LimitRange to limit denial-of-wallet/resource exhaustion impact.",
        ],
        "recommended_security_context": {
            "runAsNonRoot": True,
            "allowPrivilegeEscalation": False,
            "readOnlyRootFilesystem": True,
            "capabilities": {"drop": ["ALL"]},
            "seccompProfile": {"type": "RuntimeDefault"},
        },
        "test_steps": [
            "Run tenant application smoke tests with only DNS and approved egress allowed.",
            "Verify kube-apiserver, metadata, runtime sockets, and unrelated services are unreachable.",
        ],
    },
]


def get_policy_templates_payload() -> dict:
    return {
        "packs": copy.deepcopy(PACKS),
        "templates": copy.deepcopy(TEMPLATES),
        "total": len(TEMPLATES),
    }
